// Copyright 2020 Silicon Laboratories, Inc.
//
//

/********************************************************************
 * Autogenerated file, do not edit.
 *******************************************************************/

#ifndef __GATT_DB_H
#define __GATT_DB_H

#include "bg_gattdb_def.h"

extern const struct bg_gattdb_def bg_gattdb_data;

#define gattdb_service_changed_char             3
#define gattdb_database_hash                    6
#define gattdb_client_support_features          8
#define gattdb_manufacturer_name_string         11
#define gattdb_model_number_string             13
#define gattdb_serial_number_string            15
#define gattdb_firmware_revision_string         17
#define gattdb_device_name                     20
#define gattdb_appearance                      22
#define gattdb_light_state                     25
#define gattdb_trigger_source                  28
#define gattdb_source_address                  31

#endif
